"""canonical schema

Revision ID: 0001
Revises:
Create Date: 2026-07-07

Hand-written DDL, not autogenerated -- this is the checkpoint every attendee
resets to. Later migrations build on it live: 0002 adds RLS, 0003 adds an
index on status.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # One statement per op.execute -- cleaner history, easier to review.
    op.execute("CREATE SCHEMA IF NOT EXISTS app")
    # uuid + gen_random_uuid() needs no extension (PG13+) and skips the SERIAL
    # sequence-grant issue. owner/status exist from the start for RBAC. Other
    # fields are hand-entered for now; ai_parse_document fills them in later.
    op.execute(
        """
        CREATE TABLE app.receipts (
            id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            owner      text        NOT NULL,
            filename   text        NOT NULL,
            file_path  text        NOT NULL,
            merchant   text,
            amount     numeric(12,2),
            txn_date   date,
            status     text        NOT NULL DEFAULT 'submitted'
                       CHECK (status IN ('submitted','approved','rejected')),
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS app.receipts")
    op.execute("DROP SCHEMA IF EXISTS app")
